name: yadvs
services:
  postgres:
    image: postgres:16.4
    environment:
    - POSTGRES_DB=yadvs
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=P4ssword!
    ports:
    - 5433:5432
